FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=UTC

RUN apt-get update && apt-get install -y \
    curl gnupg2 lsb-release locales sudo \
    git build-essential cmake \
    python3-pip python3-colcon-common-extensions \
    python3-rosdep python3-vcstool python3-argcomplete \
    nano wget \
    && rm -rf /var/lib/apt/lists/*

RUN locale-gen en_US en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8

RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key \
  -o /usr/share/keyrings/ros-archive-keyring.gpg

RUN echo "deb [signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" \
  > /etc/apt/sources.list.d/ros2.list

RUN apt-get update && apt-get install -y \
    ros-humble-desktop \
    ros-humble-gazebo-ros-pkgs \
    ros-humble-navigation2 \
    ros-humble-nav2-bringup \
    ros-humble-ros2-control \
    ros-humble-ros2-controllers \
    && rm -rf /var/lib/apt/lists/*

RUN rosdep init || true
RUN rosdep update || true

RUN useradd -ms /bin/bash ros && echo "ros ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
USER ros

RUN pip3 install --no-cache-dir black ruff mypy numpy matplotlib

WORKDIR /workspaces/mars-rover-prop-m-blueprint
COPY infrastructure/docker/scripts/entrypoint_ros.sh /entrypoint_ros.sh
ENTRYPOINT ["/entrypoint_ros.sh"]
CMD ["bash"]
