amcl:
  use_sim_time: true

controller_server:
  use_sim_time: true
  controller_plugins: ["FollowPath"]

  FollowPath:
    plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
    desired_linear_vel: 0.18
    max_linear_accel: 0.15
    max_linear_decel: -0.15
    max_angular_accel: 0.8
    lookahead_dist: 0.5
    min_lookahead_dist: 0.2
    max_lookahead_dist: 1.0
    rotate_to_heading_angular_vel: 0.5
    use_velocity_scaled_lookahead_dist: true

planner_server:
  use_sim_time: true
  planner_plugins: ["GridBased"]

  GridBased:
    plugin: "nav2_navfn_planner/NavfnPlanner"
    tolerance: 0.2
    use_astar: true

bt_navigator:
  use_sim_time: true

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 10.0
      publish_frequency: 5.0
      resolution: 0.05
      width: 6
      height: 6
      robot_radius: 0.2

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      resolution: 0.05
      robot_radius: 0.2
