site_name: Mars Rover Prop-M Blueprint
theme:
  name: material
nav:
  - Home: README.md
  - Docs:
      - Overview: docs/00_overview.md
      - System Architecture: docs/system_architecture.md
      - ICD: docs/interface_control_document.md
      - V&V: docs/60_testing_vnv.md
      - Datasets: docs/70_datasets.md
      - Licensing: docs/80_licensing.md
      - References: docs/references.md
